"""Add conversation model

Revision ID: 1405622a3538
Revises: e8814e3d8163
Create Date: 2025-02-24 21:47:56.578108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1405622a3538'
down_revision = 'e8814e3d8163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###
